import type { Metadata } from 'next';
import { Geist, Great_Vibes, Dela_Gothic_One } from 'next/font/google';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const greatVibes = Great_Vibes({
  variable: '--font-great-vibes',
  subsets: ['cyrillic'],
  weight: ['400']
});

const delaGothic = Dela_Gothic_One({
  variable: '--font-dela-gothic',
  subsets: ['cyrillic'],
  weight: ['400'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body
        className={`${geistSans.variable} ${greatVibes.variable} ${delaGothic.variable} antialiased`}
      >
        <main> {children}</main>
      </body>
    </html>
  );
}
